// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atvCarros0609.Models;

#nullable disable

namespace atvCarros0609.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("atvCarros0609.Veiculos", b =>
                {
                    b.Property<int>("veiculosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("veiculosId"), 1L, 1);

                    b.Property<string>("corVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("corVe");

                    b.Property<string>("modeloVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modeloVe");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("placa");

                    b.Property<string>("proprietario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("proprietario");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.HasKey("veiculosId");

                    b.ToTable("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
